### PR TITLE
Big pull request

### PR DESCRIPTION
**Pull request by lauffenp**
Have you really not seen any of these changes? I don't know why my branch is called img...

Oops. Maybe I don't really understand github.

### CODE REVIEW

**Comment by laufetc** [comment]
Well, I don't know what I'm doing, but I "merged" it.

**Comment by laufetc** [comment]
Now, how do I get this updated in my own file system?

**Comment by lauffenp** [comment]
Like on your local repo? I think you push it....?  So I guess that is what
sounds backwards to me.

**Comment by lauffenp** [comment]
And you know to start it you need mongo server up and then just write 'npm start' in the terminal

**Comment by laufetc** [comment]
Where is the "push" button ?   (on the Github/OCSRoller website)

**Comment by lauffenp** [comment]
nawwww.... looking here I think it is a git-fetch command.

https://help.github.com/articles/fetching-a-remote/

**Comment by lauffenp** [comment]
In the command line that should be 'git fetch origin'.

Where my origin is, you may have something different. Run 'git remote -v'
and see what it says before the url of the repository.

**Comment by lauffenp** [comment]
...ok I think I understand git a bit better now. At least for my own apps.

Are you still having problems seeing what I've done?

We could fire up a heroku app and deploy changes to that to make it easier
to test.

**Comment by laufetc** [comment]
I was able to get your entire "chunk" of code onto my site.  So, maybe Git
is a bit clearer to me.  But, I show a "master" and an "img" set and they
seem to be merged, but also show as 2 separate items... I don't understand
that.  I thought that if they merged they would reduce to one.  So, maybe
there is still something that needs to be done, but I don't know what it
is.  Do you see both the master and the img sets?

Being the methodical (some would say slow) guy that I am, I am working my
way through your code.  I am very impressed with all that you've done!  I
didn't expect to have all of that in there.

For some reason I didn't just launch the whole thing at once.  Maybe I
still will "just do it" and see what happens...

It is OK with me to deploy it to Heroku; do you want me to do it?   The
last time I deployed to Heroku a test case, it was very easy... but I
didn't do a Node app, just a very small Ruby app.  I don't want to slow
down your progress with my methodicalness (aka slowness).

Love,
Dad

**Comment by lauffenp** [comment]
The master and img are wrong, in my opinion. Maybe I should create a branch
that I am updating and you 'merge' them when you see fit. That seems to be
how we have it working, but it was accidental.

I don't think it is worth deploying to heroku yet...

I'll probably try and crank this out a bit more tomorrow, so you can expect
more git notices from me...

Love,
Phil

**Comment by lauffenp** [comment]
Also, we maybe should try to be a little more professional on this forum as its currently public...

If anyone else joins they'll probably want us to tell them that we love them too.

**Pull request merged**
